document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig testslide packages
  description: ELN Extras packages for Python testing
  maintainer: meta-sig
  packages:
    - python3-testslide
  labels:
    - eln-extras
