document: feedback-pipeline-workload
version: 1
data:
  name: romaingeissler1a packages
  description: romaingeissler1a EPEL packages
  maintainer: romaingeissler1a
  packages:
    - msmtp
  labels:
    - eln-extras
