document: feedback-pipeline-workload
version: 1
data:
  name: jankratochvil packages
  description: jankratochvil EPEL packages
  maintainer: jankratochvil
  packages:
    - inotify-tools
  labels:
    - eln-extras
