document: feedback-pipeline-workload
version: 1
data:
  name: kimheino packages
  description: kimheino EPEL packages
  maintainer: kimheino
  packages:
    - foomuuri
    - foosnapper
    - munin
    - munin-apache
    - munin-cgi
    - munin-node
    - munin-plugins-ruby
  labels:
    - eln-extras
