document: feedback-pipeline-workload
version: 1
data:
  name: LXQt Desktop
  description: LXQt Desktop ELN Extras packages
  maintainer: lxqt-sig
  packages:
    # desktop components
    - lxqt-about
    - lxqt-admin
    - lxqt-archiver
    - lxqt-build-tools
    - lxqt-config
    - lxqt-globalkeys
    - lxqt-notificationd
    - lxqt-openssh-askpass
    - lxqt-panel
    - lxqt-policykit
    - lxqt-powermanagement
    - lxqt-qtplugin
    - lxqt-runner
    - lxqt-session
    - lxqt-sudo
    - lxqt-themes
    - lxqt-themes-fedora
    - lxqt-wallet
    - lxqt-wayland-session
    - pcmanfm-qt
    - qps
    - qterminal
    - screengrab
    - xdg-desktop-portal-lxqt
    # miriway is the default compositor
    - initial-setup-gui-wayland-miriway
    - lxqt-miriway-session
    - sddm-wayland-miriway
    # applications
    - featherpad
    - lximage-qt
    - pavucontrol-qt
    - qalculate-qt
    - qpdfview
    - sddm-conf
    - transmission-qt
  labels:
    - eln-extras
