document: feedback-pipeline-workload
version: 1
data:
  name: mhlavink packages
  description: mhlavink EPEL packages
  maintainer: mhlavink
  packages:
    - arm-none-eabi-gcc-cs
  arch_packages:
    aarch64:
      - nut
      - nut-cgi
      - nut-client
      - nut-monitor
      - nut-xml
    ppc64le:
      - nut
      - nut-cgi
      - nut-client
      - nut-monitor
      - nut-xml
    x86_64:
      - nut
      - nut-cgi
      - nut-client
      - nut-monitor
      - nut-xml
  labels:
    - eln-extras
