document: feedback-pipeline-workload
version: 1
data:
  name: rjarry packages
  description: rjarry EPEL packages
  maintainer: rjarry
  packages: []
  arch_packages:
    aarch64:
      - grout
    x86_64:
      - grout
  labels:
    - eln-extras
