document: feedback-pipeline-workload
version: 1
data:
  name: matthickford packages
  description: matthickford EPEL packages
  maintainer: matthickford
  packages:
    - git-credential-oauth
  labels:
    - eln-extras
