document: feedback-pipeline-workload
version: 1
data:
  name: pixelsergey packages
  description: pixelsergey EPEL packages
  maintainer: pixelsergey
  packages:
    - meow
  labels:
    - eln-extras
