document: feedback-pipeline-workload
version: 1
data:
  name: leoswaldo packages
  description: leoswaldo EPEL packages
  maintainer: leoswaldo
  packages: []
  arch_packages:
    aarch64:
      - fluent-bit
    x86_64:
      - fluent-bit
  labels:
    - eln-extras
