document: feedback-pipeline-workload
version: 1
data:
  name: ELN Extras Multimedia
  description: Multimedia SIG ELN Extras packages
  maintainer: multimedia-sig
  packages:
    - glad2
    - ladspa-devel
    - lv2-devel
    - minidlna
    - mpv
    - uxplay
    - vamp-plugin-sdk-devel
  arch_packages:
    aarch64:
      - libva-nvidia-driver
      - mediainfo
    ppc64le:
      - mediainfo
    x86_64:
      - libva-nvidia-driver
      - mediainfo
  labels:
    - eln-extras
