document: feedback-pipeline-workload
version: 1
data:
  name: rcallicotte packages
  description: rcallicotte EPEL packages
  maintainer: rcallicotte
  packages:
    - cgit
    - lzip
    - mirmon
    - mirmon-httpd
    - painless-password-rotation
    - tidy
    - umoci
  labels:
    - eln-extras
