document: feedback-pipeline-workload
version: 1
data:
  name: kwizart packages
  description: kwizart EPEL packages
  maintainer: kwizart
  packages:
    - akmods
    - dvblast
    - most
    - multicat
    - sleuthkit
    - tegrarcm
    - xmount
  arch_packages:
    x86_64:
      - libva-intel-hybrid-driver
  labels:
    - eln-extras
