document: feedback-pipeline-workload
version: 1
data:
  name: jruzicka packages
  description: jruzicka EPEL packages
  maintainer: jruzicka
  packages:
    - knot
    - knot-dnssecutils
    - knot-module-dnstap
    - knot-module-geoip
    - knot-utils
  arch_packages:
    aarch64:
      - knot-resolver
      - knot-resolver-module-dnstap
      - knot-resolver-module-http
    x86_64:
      - knot-resolver
      - knot-resolver-module-dnstap
      - knot-resolver-module-http
  labels:
    - eln-extras
