document: feedback-pipeline-workload
version: 1
data:
  name: ahaupt packages
  description: ahaupt EPEL packages
  maintainer: ahaupt
  packages:
    - ansible-collection-ansible-utils
  labels:
    - eln-extras
