document: feedback-pipeline-workload
version: 1
data:
  name: alexsaezm packages
  description: alexsaezm EPEL packages
  maintainer: alexsaezm
  packages:
    - govulncheck
  labels:
    - eln-extras
