document: feedback-pipeline-workload
version: 1
data:
  name: dherrera packages
  description: dherrera EPEL packages
  maintainer: dherrera
  packages:
    - forgejo-runner
  labels:
    - eln-extras
