document: feedback-pipeline-workload
version: 1
data:
  name: ron packages
  description: ron EPEL packages
  maintainer: ron
  packages:
    - samtools
  arch_packages:
    aarch64:
      - bcftools
    ppc64le:
      - bcftools
    x86_64:
      - bcftools
  labels:
    - eln-extras
