document: feedback-pipeline-workload
version: 1
data:
  name: sentry packages
  description: sentry EPEL packages
  maintainer: sentry
  packages: []
  arch_packages:
    aarch64:
      - zig
    x86_64:
      - zig
  labels:
    - eln-extras
