document: feedback-pipeline-workload
version: 1
data:
  name: tartare packages
  description: tartare EPEL packages
  maintainer: tartare
  packages:
    - ascii
    - todocli
    - tripwire
  labels:
    - eln-extras
