document: feedback-pipeline-workload
version: 1
data:
  name: naccyde packages
  description: naccyde EPEL packages
  maintainer: naccyde
  packages: []
  arch_packages:
    aarch64:
      - bpfilter
    x86_64:
      - bpfilter
  labels:
    - eln-extras
