document: feedback-pipeline-workload
version: 1
data:
  name: ralphlange packages
  description: ralphlange EPEL packages
  maintainer: ralphlange
  packages:
    - procServ
  labels:
    - eln-extras
