document: feedback-pipeline-workload
version: 1
data:
  name: linkdupont packages
  description: linkdupont EPEL packages
  maintainer: linkdupont
  packages:
    - kcat
  arch_packages:
    aarch64:
      - swift-lang
    x86_64:
      - swift-lang
  labels:
    - eln-extras
