document: feedback-pipeline-workload
version: 1
data:
  name: sergesanspaille packages
  description: sergesanspaille EPEL packages
  maintainer: sergesanspaille
  packages:
    - offlineimap
  labels:
    - eln-extras
