document: feedback-pipeline-workload
version: 1
data:
  name: adrienverge packages
  description: adrienverge EPEL packages
  maintainer: adrienverge
  packages:
    - yamllint
  labels:
    - eln-extras
