document: feedback-pipeline-workload
version: 1
data:
  name: pemensik packages
  description: pemensik EPEL packages
  maintainer: pemensik
  packages:
    - ethq
    - flamethrower
    - getdns-utils
  arch_packages:
    aarch64:
      - dnsjit
    x86_64:
      - dnsjit
  labels:
    - eln-extras
