document: feedback-pipeline-workload
version: 1
data:
  name: mmckinst packages
  description: mmckinst EPEL packages
  maintainer: mmckinst
  packages:
    - emacs-yaml-mode
    - fex
    - fpdns
    - mg
    - nawk
  arch_packages:
    x86_64:
      - e3
  labels:
    - eln-extras
