document: feedback-pipeline-workload
version: 1
data:
  name: timhansen46 packages
  description: timhansen46 EPEL packages
  maintainer: timhansen46
  packages:
    - mod_auth_cas
  labels:
    - eln-extras
