document: feedback-pipeline-workload
version: 1
data:
  name: suve packages
  description: suve EPEL packages
  maintainer: suve
  packages:
    - dumb-init
    - firejail
    - jc
    - rmlint
    - rmlint-gui
    - vrms-rpm
  arch_packages:
    aarch64:
      - lazarus
      - lazarus-ide
      - lazarus-lcl-gtk3
      - lazarus-lcl-qt6
      - liquidctl
    ppc64le:
      - lazarus
      - lazarus-ide
      - lazarus-lcl-gtk3
      - lazarus-lcl-qt6
      - liquidctl
    x86_64:
      - lazarus
      - lazarus-ide
      - lazarus-lcl-gtk3
      - lazarus-lcl-qt6
      - liquidctl
  labels:
    - eln-extras
