document: feedback-pipeline-workload
version: 1
data:
  name: richardfearn packages
  description: richardfearn EPEL packages
  maintainer: richardfearn
  packages:
    - clide
    - colordiff
    - disktype
    - txt2regex
    - whowatch
  arch_packages:
    aarch64:
      - ncdu
    x86_64:
      - ncdu
  labels:
    - eln-extras
