document: feedback-pipeline-workload
version: 1
data:
  name: zsun packages
  description: zsun EPEL packages
  maintainer: zsun
  packages: []
  arch_packages:
    aarch64:
      - onedrive
    x86_64:
      - onedrive
  labels:
    - eln-extras
