document: feedback-pipeline-workload
version: 1
data:
  name: sshnaidm packages
  description: sshnaidm EPEL packages
  maintainer: sshnaidm
  packages:
    - ansible-collection-containers-podman
  labels:
    - eln-extras
