document: feedback-pipeline-workload
version: 1
data:
  name: thomas-dickey packages
  description: thomas-dickey EPEL packages
  maintainer: thomas-dickey
  packages:
    - luit
    - mawk
    - vile
    - xvile
    - vttest
  labels:
    - eln-extras
