document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Debuggers packages
  description: Unwanted Debuggers packages
  maintainer: rhel-sst-pt-perf-debug
  unwanted_source_packages:
    - babeltrace
  unwanted_packages:
    - babeltrace2
  labels:
    - eln
