document: feedback-pipeline-workload
version: 1
data:
  name: DHCP Client
  description: DHCP Client software
  maintainer: rhel-stacks-services-scripting
  packages:
    - dhcpcd
  labels:
    - eln
    - c10s
