document: feedback-pipeline-workload
version: 1
data:
  name: RDMA Stack Appstream Packages
  description: RDMA Stack - Packages should be in AppStream
  maintainer: rhel-sst-network-drivers
  packages:
    - openmpi
    - openmpi-devel
    - openmpi-java
    - mpich
    - mpich-autoload
    - mpich-devel
    - mpich-doc
  labels:
    - eln
    - c10s
