document: feedback-pipeline-workload
version: 1
data:
  name: Messaging clients
  description: Instant messaging clients, e.g. IRC, Jabber, etc.
  maintainer: rhel-net-perf
  packages:
    - irssi
  labels:
    - eln
    - c10s
