document: feedback-pipeline-unwanted
version: 1
data:
  name: Core Services Plumbers - Blocked packages
  description: Core Services Plumbers - Packages which should not be in ELN
  maintainer: rhel-sst-cs-plumbers
  unwanted_source_packages:
    - atlas
    - libnice
    - libtar
    - redhat-lsb
    - rtkit
    # compat package
    - tree-sitter0.25
  unwanted_packages:
    - emacs-terminal
    - network-scripts
    - systemd-tests
  labels:
    - eln
    - c10s
