document: feedback-pipeline-workload
version: 1
data:
  name: Graph visualization
  description: Graph visualization software
  maintainer: rhel-net-perf
  packages:
    - graphviz
  labels:
    - eln
    - c10s
