document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - NGINX
  description: CS Stacks - NGINX
  maintainer: rhel-stacks-web-servers
  packages:
    - nginx
    - nginx-all-modules
  labels:
    - eln
    - c10s
