document: feedback-pipeline-workload
version: 1
data:
  name: GeoLite2
  description: GeoIP databases
  maintainer: rhel-net-perf
  packages:
    - geolite2-city
    - geolite2-country
  labels:
    - c10s
