document: feedback-pipeline-unwanted
version: 1
data:
  name: Exclude multilib-rpm-config
  description: There are no more 32-bit builds for RHEL, so this package is not needed.
  maintainer: rhel-sst-pt-llvm-rust-go
  unwanted_packages:
    - multilib-rpm-config
  labels:
    - eln
