document: feedback-pipeline-unwanted
version: 1
data:
  name: GlusterFS storage unwanted
  description: Unwanted GlusterFS storage packages
  maintainer: rhel-sst-rh-ceph-storage
  unwanted_source_packages:
    - glusterfs
  labels:
    - eln
    - c10s
