document: feedback-pipeline-workload
version: 1
data:
  name: Cloud Experience Integrations for RHEL
  description: Software that makes RHEL more integrated with various clouds
  maintainer: rhel-sst-cloudexperience
  packages: []
  arch_packages:
    aarch64:
      - awscli2
    x86_64:
      - awscli2
  package_placeholders:
    - srpm_name: opentelemetry-collector
      rpms:
        - rpm_name: opentelemetry-collector
          description: iOpenTelemetry Collector
  labels:
    - eln
    - c10s
